# Generated by Django 3.0.4 on 2020-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.CharField(max_length=100, verbose_name='Discount Agreement')),
                ('period', models.TextField(verbose_name='Period of agreement')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('id_negotiator', models.IntegerField(verbose_name='Responsible person')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'agreements',
            },
        ),
    ]
