# Generated by Django 3.0.4 on 2020-03-22 14:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='period',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Period of agreement'),
        ),
    ]
