# Generated by Django 3.0.4 on 2020-03-22 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200322_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='period',
        ),
        migrations.AddField(
            model_name='agreement',
            name='period_finish',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 19, 56, 55, 712976), verbose_name='Finish period of agreement'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 19, 56, 55, 712976), verbose_name='Start period of agreement'),
        ),
    ]
