# Generated by Django 3.0.4 on 2020-03-22 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200322_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='period_finish',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 20, 9, 29, 270707), verbose_name='Finish period of agreement'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 20, 9, 29, 270707), verbose_name='Start period of agreement'),
        ),
    ]
