# Generated by Django 3.0.4 on 2020-03-22 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200322_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='period_finish',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 22, 58, 27, 99300), verbose_name='Finish period of agreement'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 20, 58, 27, 99300, tzinfo=utc), verbose_name='Start period of agreement'),
        ),
    ]
