# Generated by Django 3.0.4 on 2020-03-22 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200323_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='agreement',
            new_name='agreement_name',
        ),
        migrations.AlterField(
            model_name='periods',
            name='period_finish',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 1, 47, 11, 362216), verbose_name='Finish period of agreement'),
        ),
        migrations.AlterField(
            model_name='periods',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 23, 47, 11, 362216, tzinfo=utc), verbose_name='Start period of agreement'),
        ),
    ]
